const CategorySampleData = [
    {"categoryName": "Technology", "categoryDescription": "Delicious recipes and food trends."},
    {"categoryName": "Health", "categoryDescription": "Creative expressions from artists globally."},
    {"categoryName": "Education", "categoryDescription": "Tips and tricks to stay healthy."},
    {"categoryName": "Travel", "categoryDescription": "Delicious recipes and food trends."},
    {"categoryName": "Food", "categoryDescription": "Updates on sports events and news."},
    {"categoryName": "Entertainment", "categoryDescription": "Managing your finances effectively."},
    {"categoryName": "Sports", "categoryDescription": "Exploring the best destinations worldwide."},
    {"categoryName": "Finance", "categoryDescription": "The latest advancements in the field."},
    {"categoryName": "Environment", "categoryDescription": "Keeping up with movies, music, and more."},
    {"categoryName": "Art", "categoryDescription": "Insights into modern educational methods."}
]

const ProductSampleData = [
    {"productName": "Smartphone", "productDescription": "A top-tier option for enthusiasts.", "categoryId": 1},
    {"productName": "Fitness Tracker", "productDescription": "Tailored to meet your unique needs.", "categoryId": 2},
    {"productName": "Online Course", "productDescription": "A high-quality product for everyday use.", "categoryId": 3},
    {"productName": "Travel Backpack", "productDescription": "A high-quality product for everyday use.", "categoryId": 4},
    {"productName": "Gourmet Chocolate", "productDescription": "Tailored to meet your unique needs.", "categoryId": 5},
    {"productName": "Streaming Subscription", "productDescription": "Tailored to meet your unique needs.", "categoryId": 6},
    {"productName": "Football", "productDescription": "Combines functionality with aesthetics.", "categoryId": 7},
    {"productName": "Budgeting App", "productDescription": "Perfect for enhancing your lifestyle.", "categoryId": 8},
    {"productName": "Reusable Water Bottle", "productDescription": "Tailored to meet your unique needs.", "categoryId": 9},
    {"productName": "Oil Painting Kit", "productDescription": "A high-quality product for everyday use.", "categoryId": 10},
    {"productName": "Laptop", "productDescription": "Compact, durable, and reliable.", "categoryId": 1},
    {"productName": "Yoga Mat", "productDescription": "Compact, durable, and reliable.", "categoryId": 2},
    {"productName": "E-Learning Subscription", "productDescription": "Perfect for enhancing your lifestyle.", "categoryId": 3},
    {"productName": "Luggage Set", "productDescription": "Designed for maximum performance and comfort.", "categoryId": 4},
    {"productName": "Organic Coffee", "productDescription": "An excellent choice for hobbyists and professionals.", "categoryId": 5},
    {"productName": "Movie Ticket", "productDescription": "Designed for maximum performance and comfort.", "categoryId": 6},
    {"productName": "Basketball", "productDescription": "Tailored to meet your unique needs.", "categoryId": 7},
    {"productName": "Stock Analysis Software", "productDescription": "Compact, durable, and reliable.", "categoryId": 8},
    {"productName": "Solar Charger", "productDescription": "Offers great value for its price.", "categoryId": 9},
    {"productName": "Sketchbook", "productDescription": "Tailored to meet your unique needs.", "categoryId": 10},
    {"productName": "Smartphone sample", "productDescription": "A top-tier option for enthusiasts.", "categoryId": 3},
    {"productName": "Fitness Tracker sample", "productDescription": "Tailored to meet your unique needs.", "categoryId": 7},
    {"productName": "Online Course sample", "productDescription": "A high-quality product for everyday use.", "categoryId": 1},
    {"productName": "Travel Backpack sample", "productDescription": "A high-quality product for everyday use.", "categoryId": 10},
    {"productName": "Gourmet Chocolate sample", "productDescription": "Tailored to meet your unique needs.", "categoryId": 4},
    {"productName": "Streaming Subscription sample", "productDescription": "Tailored to meet your unique needs.", "categoryId": 6},
    {"productName": "Football sample", "productDescription": "Combines functionality with aesthetics.", "categoryId": 2},
    {"productName": "Budgeting App sample", "productDescription": "Perfect for enhancing your lifestyle.", "categoryId": 9},
    {"productName": "Reusable Water Bottle sample", "productDescription": "Tailored to meet your unique needs.", "categoryId": 8},
    {"productName": "Oil Painting Kit sample", "productDescription": "A high-quality product for everyday use.", "categoryId": 5},
    {"productName": "Laptop sample", "productDescription": "Compact, durable, and reliable.", "categoryId": 2},
    {"productName": "Yoga Mat sample", "productDescription": "Compact, durable, and reliable.", "categoryId": 4},
    {"productName": "E-Learning Subscription sample", "productDescription": "Perfect for enhancing your lifestyle.", "categoryId": 7},
    {"productName": "Luggage Set sample", "productDescription": "Designed for maximum performance and comfort.", "categoryId": 1},
    {"productName": "Organic Coffee sample", "productDescription": "An excellent choice for hobbyists and professionals.", "categoryId": 10},
    {"productName": "Movie Ticket sample", "productDescription": "Designed for maximum performance and comfort.", "categoryId": 3},
    {"productName": "Basketball sample", "productDescription": "Tailored to meet your unique needs.", "categoryId": 9},
    {"productName": "Stock Analysis Software sample", "productDescription": "Compact, durable, and reliable.", "categoryId": 5},
    {"productName": "Solar Charger sample", "productDescription": "Offers great value for its price.", "categoryId": 6},
    {"productName": "Sketchbook sample", "productDescription": "Tailored to meet your unique needs.", "categoryId": 8}

]
