version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-ts-app
    ports:
      - "${MAIN_PORT}:${MAIN_PORT}"  # Use MAIN_PORT from .env
    environment:
      NODE_ENV: production
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_DIALECT: ${DB_DIALECT}
      DB_PORT: ${DB_PORT}
    volumes:
      - .:/app
      - /app/node_modules
    command: ["node", "dist/index.js"]
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
